name: Build and Push to ghcr.io

on:
  push:
    branches:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - name: Install ko
        uses: ko-build/setup-ko@v0.8

      - name: Authenticate to ghcr.io
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image (non-main branches)
        if: github.ref != 'refs/heads/main'
        env:
          KO_DOCKER_REPO: ghcr.io/jackweinbender
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          # don't set latest tag for non-main branches
          ko build ./ \
            -t "${{ github.sha }}" \
            -t "${GITHUB_REF_NAME//\//-}" \
            --platform linux/amd64,linux/arm64 -B

      - name: Build and push image (main branch)
        if: github.ref == 'refs/heads/main'
        env:
          KO_DOCKER_REPO: ghcr.io/jackweinbender
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          ko build ./ \
            -t "${{ github.sha }}" \
            -t "${GITHUB_REF_NAME//\//-}" \
            -t "latest" \
            --platform linux/amd64,linux/arm64 -B
