name: Build and Push to ghcr.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "stable"

      - name: Install ko
        uses: ko-build/setup-ko@v0.8

      - name: Authenticate to ghcr.io
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        env:
          KO_DOCKER_REPO: ghcr.io/jackweinbender/secrets-operator
        run: >
          ko build ./
            -t "${{ github.sha }}"
            -t "${{ github.ref_name }}"
            -t "latest"
            --platform linux/amd64,linux/arm64 -B
